"""Build/verify a sieve-near certificate for one repository leaf at a target exponent.

The repository leaf input is regenerated by its own code (make_endgame,
replace_far, apply_collective); sieve rows are added from rational test
parameters; certificates are multi-threshold bisection trees (certificate.py).
"""
import sys, os, math, pickle
from pathlib import Path
from fractions import Fraction as Q
import numpy as np
HERE = Path(__file__).resolve().parent
FR = HERE.parent/'frontier'
sys.path.insert(0, str(FR)); sys.path.insert(0, str(FR.parent/'core'/'code')); sys.path.insert(0, str(HERE))
import far_enclosures  # noqa: F401  (path side effects)
from far_enclosures import make_endgame, replace_far, parse_params
from collective_model import apply_collective
from sieve_inputs import SieveNearTest
from certificate import LeafData, S
import certificate3 as C2
from certificate3 import CannotCertify
import propose_params

S1_GRID = Q(1, 50)


def spec_of(inp):
    return dict(case=dict(inp['case']), gap=(dict(inp['gap']) if inp['gap'] else None), height=inp['height'],
                method=inp['method'], ordinary_lower=inp['ordinary_lower'],
                second=({k: inp['second'][k] for k in ('lo', 'hi', 'n')} if inp['second'] else None))


def regen(inp, L):
    sp = spec_of(inp); par = parse_params(inp)
    out = make_endgame(sp, L, par, inp['lambda_den'])
    if out is None:
        return None
    if 'far_parameters' in inp:
        out = replace_far(out, inp['far_parameters'])
    if 'collective_envelope' in inp:
        out = apply_collective(out, [r['parameters'] for r in inp['collective_envelope']['cohorts']])
    return out


def regen_refined(inp, L):
    """regen followed by the refined real/real third-family bound (third_refine.py)."""
    out = regen(inp, L)
    if out is None:
        return None
    import third_refine
    return third_refine.refine_third(out)


def safe_anchor(inp):
    """Largest grid value not above the first-zero lower bound: every zero has lambda >= it."""
    a = Q(inp['case']['lo'])
    return (a/S1_GRID).__floor__()*S1_GRID


_TESTS = {}


def sieve_test(params):
    key = tuple(sorted(params.items()))
    if key not in _TESTS:
        _TESTS[key] = SieveNearTest(Q(params['gamma']), Q(params['g1']), Q(params['t0']), Q(params['mu']),
                                    Q(params['s']), Q(params['s1']))
    return _TESTS[key]


def sieve_rows(inp, test):
    rows = inp['rows']
    v = []
    for r in rows:
        if r[1] == 'infinity' or Q(r[0]) < test.s:
            v.append(0)
        else:
            v.append(max(0, test.feature(Q(r[1]))))
    d, D = test.gram()
    return dict(d=d, D=D, v=v)


ANCHOR_STEP = Q(1, 20)


def anchor_grid_below(lam, s1):
    """Largest grid anchor <= lam, and at least s1 + ANCHOR_STEP."""
    a = (Q(lam)/ANCHOR_STEP).__floor__()*ANCHOR_STEP
    return a if a >= s1+ANCHOR_STEP else None


# ------------------------------------------------------------ graded rows (inside leaves)
DELTA_GRID = Q(1, 200)


def _delta_floor(delta):
    return (Q(delta)/DELTA_GRID).__floor__()*DELTA_GRID


def _family_term(test, n, hi, anchor, D):
    """n characters with parameter in [anchor, hi] and response anchor `anchor` (<= s)."""
    if anchor == test.s:
        return (int(n), max(0, test.feature_at(hi, anchor)), D)
    dn = test.diag_norm(_delta_floor(test.s-anchor))
    if dn is None:
        return (int(n), 0, D)
    return (int(n), max(0, test.feature_at(hi, anchor)), dn)


def graded_row(inp, params, families=True, mu_range=None, hidden=False, sec_anchor='a', dz_range=None):
    """Graded near row with reference anchor s (sieve-majorant-near.md section 2b).

    Every character uses the response anchor min(its lower parameter, s): ordinary bins
    [lo,hi] below s use anchor lo, feature (F(hi-lo)-1/6)/sqrt(I D) and diagonal D(s-lo);
    bins above s use anchor s and diagonal D(0).  The first family (anchor min(lambda1^lo, s))
    and a reserved second family (also anchor min(lambda1^lo, s)) are included as fixed terms."""
    if families is True or families == 'shifted':
        assert inp['height'] == 'inside'
    test = sieve_test(params)
    s, s1 = test.s, test.s1
    assert s1 == safe_anchor(inp)
    a, b = Q(inp['case']['lo']), Q(inp['case']['hi'])
    assert s1 <= a <= b and Q(inp['ordinary_lower']) >= a
    d, D = test.gram()
    v, Dv = [], []
    for r in inp['rows']:
        if r[1] == 'infinity':
            v.append(0); Dv.append(D); continue
        lo, hi = Q(r[0]), Q(r[1])
        assert lo >= a
        if lo >= s:
            v.append(max(0, test.feature(hi))); Dv.append(D)
            continue
        dn = test.diag_norm(_delta_floor(s-lo))
        if dn is None:
            v.append(0); Dv.append(D)
        else:
            v.append(max(0, test.feature_at(hi, lo))); Dv.append(dn)
    if not families:
        return dict(d=d, D=D, v=v, Dv=Dv)
    if families == 'second':
        # outside first zero: only the reserved height-one second family joins the row
        fam = []
    elif families == 'outside_first':
        # outside first zero in the family row (review §8): anchor s1, no sieve part; the first
        # family's local zeros (hidden columns) keep feature 0
        assert s == s1 and all(h == 0 for h in test.h)
        fam = [_family_term(test, inp['n'], b, min(a, s), D)]
    elif families == 'shifted':
        # anchor s = the repository's validated shift min(1.9, lambda', global lambda2) >= lambda1^lo:
        # the first zero lies right of the test point and is retained explicitly (note §2f)
        lp = Q(inp['gap']['lo']) if inp.get('gap') else Q(inp['case']['lp'])
        assert s == Q(inp['shift']) and s <= lp and s <= Q(inp['case']['source_l2']) and s >= a
        fam = [(int(inp['n']), max(0, test.shifted_first_feature(a, b, inp['case']['kind'] == 'rc')), D)]
    elif dz_range is not None:
        # complex first family with a finite gap for its second zero lambda' (PROOF.md §6.5): each
        # character carries the entries of rho1 and of its other zero, at normalized height difference
        # in dz_range; family row only (s = s1, H = 0)
        gap = inp.get('gap')
        assert families is True and s == s1 and all(h == 0 for h in test.h) and mu_range is None
        assert inp['height'] == 'inside' and inp['case']['kind'] == 'complex'
        assert gap and gap['hi'] != 'infinity'
        lo_z, hi_z = dz_range
        fam = test.second_zero_terms(inp['n'], a, b, Q(gap['lo']), Q(gap['hi']), Q(lo_z),
                                     None if hi_z is None else Q(hi_z))
    elif mu_range is not None and inp['case']['kind'] == 'rc' and s == s1 and families is True:
        # real first character with a nonreal zero: the pair (chi1, +-gamma1) for mu1 in mu_range
        assert int(inp['n']) == 1
        lo_mu, hi_mu = mu_range
        fam = [test.pair_term(a, b, Q(lo_mu), None if hi_mu is None else Q(hi_mu))]
    else:
        fam = [_family_term(test, inp['n'], b, min(a, s), D)]
    sec = inp['second']
    if sec:
        lo2 = Q(sec['lo'])
        assert lo2 >= a
        # anchor <= lambda1^lo (or, with sec_anchor='l2', <= the global lambda2 lower bound): every
        # zero of the family lies left of the test point, so its |gamma|<=1 representative
        # (parameter <= hi2) is retained without the strip argument
        a2 = max(a, min(Q(inp['case']['source_l2']), lo2)) if sec_anchor == 'l2' else a
        fam.append(_family_term(test, sec['n'], Q(sec['hi']), min(a2, s), D))
    row = dict(d=d, D=D, v=v, Dv=Dv, fam=fam)
    if hidden:
        # hidden columns = local height-one centers of the distinct hidden family (one vector per
        # character; its global zero is the old row's shadow term only), or (hidden='outside') the
        # outside first family's local zeros, whose vectors are asymptotically orthogonal to the
        # same characters' global-zero vectors (heights separated by the buffer); anchor s1, H = 0
        assert s == s1 and all(h == 0 for h in test.h)
        assert inp.get('identity') == 'distinct' or (hidden == 'outside' and inp['height'] == 'outside')
        row['vh'] = [0 if r[1] == 'infinity' else max(0, test.feature(Q(r[1]))) for r in inp['hidden_rows']]
        assert all(Q(r[0]) >= s1 for r in inp['hidden_rows'])
    return row


def graded_parameters(inp, s):
    """Rational test parameters for a graded row with reference anchor s."""
    s1 = safe_anchor(inp)
    if Q(s) == s1:
        return family_parameters(inp)
    return propose_params.params(s1, Q(s))


def gleafdata(inp, anchors, mu_range=None):
    """LeafData with graded rows at the given reference anchors (s1 = the family row)."""
    plist = [graded_parameters(inp, s) for s in anchors]
    return LeafData(inp, [graded_row(inp, p, mu_range=mu_range) for p in plist]), plist


def gcertify(inp, anchors, target=Q(9999999, 10000000), max_boxes=20000, min_width=1):
    ld, plist = gleafdata(inp, anchors)
    tree, mx, nb = C2.build(ld, target=target, max_boxes=max_boxes, min_width=min_width)
    return dict(rows=[dict(kind='graded', parameters=p) for p in plist], tree=tree, maximum=mx, boxes=nb)


GMENU = [Q(x, 10) for x in range(11, 30, 2)]   # 1.1, 1.3, ..., 2.9


def gmenu_for(inp, anchors):
    return [c for c in GMENU if all(abs(c-a) >= Q(3, 20) for a in anchors)]


def gadaptive_certify(inp, max_anchors=4, float_margin=0.99, max_boxes=20000, log=print, init_anchors=None):
    """Family row plus greedily chosen graded rows; rigorous certificate."""
    s1 = safe_anchor(inp)
    anchors = sorted(set([s1]+[Q(a) for a in (init_anchors or [])]))

    def worst_fn(A, starts=2, grid=12):
        ld, _ = gleafdata(inp, A)
        return float_worst(ld, starts=starts, grid=grid)[0]
    val = worst_fn(anchors, 3, 14)
    log(('gfloat', [str(a) for a in anchors], round(val, 6)))

    def greedy(anchors, val, cap, margin):
        while val >= margin and len(anchors) < cap:
            best = None
            for c in gmenu_for(inp, anchors):
                v = worst_fn(sorted(anchors+[c]))
                if best is None or v < best[0]:
                    best = (v, c)
            if best is None or best[0] >= val-1e-4:
                break
            anchors = sorted(anchors+[best[1]]); val = best[0]
            log(('ggreedy', [str(a) for a in anchors], round(val, 6)))
        return anchors, val
    anchors, val = greedy(anchors, val, max_anchors+1, float_margin)
    tries = 0
    while True:
        try:
            rec = gcertify(inp, anchors, max_boxes=max_boxes)
            rec['anchors'] = [str(a) for a in anchors]
            return rec
        except CannotCertify as e:
            log(('cert-fail', [str(a) for a in anchors], e.args[0], e.value))
            tries += 1
            if tries > 2:
                raise
            anchors2, _ = greedy(anchors, 2.0, len(anchors)+1, 0.0)
            if anchors2 == anchors:
                raise
            anchors = anchors2


def family_parameters(inp):
    import family_row
    p = family_row.propose(inp)
    p.pop('allowed', None)
    return p


def _family(inp, fam):
    if not fam:
        return []
    import family_row
    return [family_row.family_row(inp, fam)]


def leafdata(inp, anchors, fam=None):
    s1 = safe_anchor(inp)
    plist = [propose_params.params(s1, s) for s in anchors]
    sieve = _family(inp, fam)+[sieve_rows(inp, sieve_test(p)) for p in plist]
    return LeafData(inp, sieve), plist


def certify(inp, anchors, target=Q(9999999, 10000000), max_boxes=20000, min_width=1, fam=None):
    ld, plist = leafdata(inp, anchors, fam)
    tree, mx, nb = C2.build(ld, target=target, max_boxes=max_boxes, min_width=min_width)
    rec = dict(sieve_parameters=plist, tree=tree, maximum=mx, boxes=nb)
    if fam:
        rec['family_parameters'] = dict(fam)
    return rec


def verify(inp, record):
    if 'mu_split' in record:
        # rc leaves: the height of the first zero is split into ranges covering [0, infinity)
        parts = record['mu_split']
        assert parts[0]['mu_range'][0] == '0' and parts[-1]['mu_range'][1] is None
        assert all(p['mu_range'][1] == q['mu_range'][0] for p, q in zip(parts, parts[1:]))
        mx = -1; nb = 0
        for part in parts:
            m, n = verify(inp, part)
            mx = max(mx, m); nb += n
        assert mx == record['maximum']
        return mx, nb
    if 'rows' in record:
        mr = record.get('mu_range')
        sieve = []
        for rs in record['rows']:
            assert rs['kind'] == 'graded'
            sieve.append(graded_row(inp, rs['parameters'], mu_range=mr))
    else:
        sieve = _family(inp, record.get('family_parameters'))
        sieve += [sieve_rows(inp, sieve_test(p)) for p in record['sieve_parameters']]
    ld = LeafData(inp, sieve)
    mx, nb = C2.verify_tree(ld, record['tree'])
    assert mx == record['maximum']
    return mx, nb


def float_worst(ld, starts=3, grid=14, sweeps=5, seed=0):
    """Approximate global maximum over thresholds of the box-free LP (floating, proposal only)."""
    from certificate import Proposer
    P = Proposer(ld)
    ends = ld.ends
    grids = [[int(v) for v in np.unique(np.linspace(0, e, grid).astype(np.int64))] for e in ends]

    def val(t):
        box = [(x, x) for x in t]
        bud = P.fbudgets(box)
        if min(bud) < 0:
            return -1.0, None
        A = np.vstack([P.Wf, P.Cf]+[P.fcosts(k, b) for k, (a, b) in enumerate(box)])
        import highspy
        m, n = A.shape
        h = highspy.Highs(); h.setOptionValue('output_flag', False); h.setOptionValue('simplex_strategy', 4)
        lp = highspy.HighsLp(); lp.num_col_ = n; lp.num_row_ = m
        lp.col_cost_ = -P.Gf; lp.col_lower_ = np.zeros(n); lp.col_upper_ = np.full(n, highspy.kHighsInf)
        lp.row_lower_ = np.full(m, -highspy.kHighsInf); lp.row_upper_ = np.array([ld.F/S, 2.0]+bud)
        lp.a_matrix_.format_ = highspy.MatrixFormat.kColwise
        lp.a_matrix_.start_ = np.arange(0, m*n+1, m); lp.a_matrix_.index_ = np.tile(np.arange(m), n)
        lp.a_matrix_.value_ = np.ascontiguousarray(A.T).reshape(-1)
        h.passModel(lp); h.run()
        if h.getModelStatus() != highspy.HighsModelStatus.kOptimal:
            return -1.0, None
        return -h.getInfo().objective_function_value+(ld.first+ld.final)/S, np.array(h.getSolution().col_value)
    rng = np.random.default_rng(seed)
    best = (-np.inf, None, None)
    for st in range(starts):
        t = [int(g[rng.integers(len(g))]) if st else int(g[len(g)//2]) for g in grids]
        cur, x = val(t)
        step = [max(1, e//(2*grid)) for e in ends]
        for sw in range(sweeps):
            imp = False
            for k in range(len(t)):
                for cand in list(grids[k])+[max(0, t[k]-step[k]), min(ends[k], t[k]+step[k])]:
                    tt = list(t); tt[k] = int(cand)
                    v, xx = val(tt)
                    if v > cur+1e-12:
                        cur, x, t, imp = v, xx, tt, True
            step = [max(1, s//3) for s in step]
            if not imp and sw > 1:
                break
        if cur > best[0]:
            best = (cur, t, x)
    return best


MIN_SPACING = Q(1, 5)


def worst_anchor(inp, x, anchors):
    """Grid anchor just below the costliest occupied ordinary bin, at least MIN_SPACING from
    existing anchors; falls back to the next costliest bin."""
    s1 = safe_anchor(inp)
    rows = inp['rows']
    cand = []
    for i, xi in enumerate(x):
        if xi <= 1e-9 or rows[i][1] == 'infinity':
            continue
        a = anchor_grid_below(Q(rows[i][0]), s1)
        if a is not None and a not in anchors:
            cand.append((xi*rows[i][3], a))
    cand.sort(reverse=True)
    for _, a in cand:
        if all(abs(a-b) >= MIN_SPACING for b in anchors):
            return a
    return None


MENU = [Q(x, 10) for x in range(9, 27, 2)]   # 0.9, 1.1, ..., 2.5


def menu_for(inp, anchors):
    s1 = safe_anchor(inp)
    return [c for c in MENU if c >= s1+Q(3, 20) and all(abs(c-a) >= Q(3, 20) for a in anchors)]


def greedy_anchors(inp, anchors, val, max_anchors, margin, worst_fn, log):
    """Add menu anchors one at a time, each time the one with the lowest floating maximum."""
    while val >= margin and len(anchors) < max_anchors:
        best = None
        for c in menu_for(inp, anchors):
            v = worst_fn(sorted(anchors+[c]))
            if best is None or v < best[0]:
                best = (v, c)
        if best is None or best[0] >= val-1e-4:
            break
        anchors = sorted(anchors+[best[1]]); val = best[0]
        log(('greedy', [str(a) for a in anchors], round(val, 6)))
    return anchors, val


def adaptive_certify(inp, max_anchors=4, float_margin=0.995, max_boxes=20000, log=print, init_anchors=(),
                     family=False):
    """Greedy menu anchors driven by the approximate global worst population; rigorous certificate.
    family=True adds the family-inclusive row at the safe anchor (family_row.py)."""
    anchors = sorted(Q(a) for a in init_anchors)
    fam = family_parameters(inp) if family else None
    if fam:
        log(('family', fam['gamma'], fam['g1']))

    def worst_fn(A, starts=2, grid=12):
        ld, _ = leafdata(inp, A, fam)
        return float_worst(ld, starts=starts, grid=grid)[0]
    ld, _ = leafdata(inp, anchors, fam)
    val = float_worst(ld)[0]
    log(('float', [str(a) for a in anchors], round(val, 6)))
    anchors, val = greedy_anchors(inp, anchors, val, max_anchors, float_margin, worst_fn, log)
    tries = 0
    while True:
        try:
            rec = certify(inp, anchors, max_boxes=max_boxes, fam=fam)
            rec['anchors'] = [str(a) for a in anchors]
            return rec
        except CannotCertify as e:
            log(('cert-fail', [str(a) for a in anchors], e.args[0], e.value))
            tries += 1
            if tries > 2:
                raise
            anchors2, _ = greedy_anchors(inp, anchors, 2.0, len(anchors)+1, 0.0, worst_fn, log)
            if anchors2 == anchors:
                raise
            anchors = anchors2


# ------------------------------------------------------------ outside regime
def regen_out(inp, L):
    nc = str(HERE.parent/'near'/'code')
    if nc not in sys.path:
        sys.path.insert(0, nc)
    import first_outside_blocks as fob
    from refine_probe import spec_from_input
    base = spec_from_input(inp)
    e = inp['extension']
    par = dict(method=e['variant'], gg=e['gG'], gz=e['gZ'], mix=e.get('mix', '0'), zeta=e.get('zeta', '3'))
    return fob.first_out_input(base, L, 'outside_buffer', par, inp['lambda_den'])


def outleaf(inp, anchors):
    import certificate_out as CO
    s1 = safe_anchor(inp)
    plist = [propose_params.params(s1, s) for s in anchors]
    sieve = [sieve_rows(inp, sieve_test(p)) for p in plist]
    return CO.OutLeaf(inp, sieve), plist


def float_worst_out(ol, starts=3, grid=14, sweeps=5, seed=0):
    import certificate_out as CO
    K = len(ol.ends)-1
    grids = [[int(v) for v in np.unique(np.linspace(0, e, grid).astype(np.int64))] for e in ol.ends]
    Gall = np.array(ol.G+ol.GH, float)/S
    nO, nH = len(ol.G), len(ol.GH)

    def val(t):
        box = [(t[0], t[0])]+[(x, x) for x in t[1:]]
        cd = CO.case_data(ol, box, (0,)*K)
        costs, CH, budgets = cd
        if min(budgets) < 0:
            return -1.0, None
        rowsA = [np.array(ol.W+ol.WH, float)/S, np.array(costs[0]+CH, float)/S, np.array([0]*nO+ol.NH, float)/S,
                 np.array(ol.cnt+[0]*nH, float)/S]
        for c in costs[1:]:
            rowsA.append(np.array(c if len(c) > nO else c+[0]*nH, float)/S)
        r = C2._lp(Gall, np.vstack(rowsA), [ol.F/S, budgets[0]/S, float(ol.ng), 2.0]+[b/S for b in budgets[1:]])
        if r is None:
            return -1.0, None
        return r[0]+(ol.first+ol.final)/S, r[2][:nO]
    rng = np.random.default_rng(seed)
    best = (-np.inf, None, None)
    for st in range(starts):
        t = [int(g[rng.integers(len(g))]) if st else int(g[len(g)//2]) for g in grids]
        cur, x = val(t)
        step = [max(1, e//(2*grid)) for e in ol.ends]
        for sw in range(sweeps):
            imp = False
            for k in range(len(t)):
                for cand in list(grids[k])+[max(0, t[k]-step[k]), min(ol.ends[k], t[k]+step[k])]:
                    tt = list(t); tt[k] = int(cand)
                    v, xx = val(tt)
                    if v > cur+1e-12:
                        cur, x, t, imp = v, xx, tt, True
            step = [max(1, s//3) for s in step]
            if not imp and sw > 1:
                break
        if cur > best[0]:
            best = (cur, t, x)
    return best


def adaptive_certify_out(inp, max_anchors=4, float_margin=0.995, max_boxes=20000, log=print, init_anchors=()):
    import certificate_out as CO
    anchors = sorted(Q(a) for a in init_anchors)

    def worst_fn(A, starts=2, grid=12):
        ol, _ = outleaf(inp, A)
        return float_worst_out(ol, starts=starts, grid=grid)[0]
    ol, _ = outleaf(inp, anchors)
    val = float_worst_out(ol)[0]
    log(('float', [str(a) for a in anchors], round(val, 6)))
    anchors, val = greedy_anchors(inp, anchors, val, max_anchors, float_margin, worst_fn, log)
    tries = 0
    while True:
        ol, plist = outleaf(inp, anchors)
        try:
            tree, mx, nb = CO.build(ol, max_boxes=max_boxes)
            return dict(sieve_parameters=plist, tree=tree, maximum=mx, boxes=nb, anchors=[str(a) for a in anchors])
        except CannotCertify as e:
            log(('cert-fail', [str(a) for a in anchors], e.args[0], e.value))
            tries += 1
            if tries > 2:
                raise
            anchors2, _ = greedy_anchors(inp, anchors, 2.0, len(anchors)+1, 0.0, worst_fn, log)
            if anchors2 == anchors:
                raise
            anchors = anchors2


# ------------------------------------------------------------ outside regime, graded rows
def goutleaf(inp, anchors, model='outside', families=False):
    """Outside-buffer leaf with graded rows.  families=False omits every family; 'second' adds the
    reserved height-one second family (anchor <= lambda1^lo); 'outside_first' additionally puts the
    outside first family into the family row at s1 (sieve part zero)."""
    import certificate_out as CO
    s1 = safe_anchor(inp)
    plist = [graded_parameters(inp, s) if (families and Q(s) == s1) else propose_params.params(s1, Q(s))
             for s in anchors]
    rows = []
    for s, p in zip(anchors, plist):
        fm = families
        if families == 'outside_first' and Q(s) != s1:
            fm = 'second' if inp.get('second') else False
        rows.append(graded_row(inp, p, families=fm))
    return CO.OutLeaf(inp, rows, model=model), plist


def gblockleaf(inp, anchors, hidden=None):
    """Hidden-family branch leaf (first zero inside) with the family row and graded rows,
    first and reserved second families included.  hidden=True (default for 'distinct' branches)
    gives the hidden global family features in the family row; elsewhere hidden columns are omitted."""
    import certificate_out as CO
    if hidden is None:
        hidden = inp.get('identity') == 'distinct' and os.environ.get('SIEVE_BLOCK_HIDDEN', '1') == '1'
    s1 = safe_anchor(inp)
    plist = [graded_parameters(inp, s) for s in anchors]
    return CO.OutLeaf(inp, [graded_row(inp, p, families=True, hidden=(hidden and Q(p['s']) == s1)) for p in plist],
                      model='block'), plist


def regen_block(ctx, L):
    """Regenerate a hidden-family branch leaf (inside_repair 'identities') at exponent L with the
    repository's make_inside_input from the captured 4.33 template, branch and parameters."""
    nc = str(HERE.parent/'near'/'code')
    if nc not in sys.path:
        sys.path.insert(0, nc)
    from inside_model import make_inside_input
    inp = make_inside_input(ctx['base'], L, ctx['br'], ctx['parameters'], ctx['den'])
    if ctx.get('far_parameters'):
        from inside_far import replace_inside_far
        inp = replace_inside_far(inp, ctx['far_parameters'])
    if ctx['br']['identity'] == 'unhidden':
        # no hidden rows: the refined real/real third bound applies as for ordinary inside leaves
        assert not inp['hidden_rows']
        import third_refine
        inp = third_refine.refine_third(inp)
    return inp


def gadaptive_certify_out(inp, max_anchors=4, float_margin=0.99, max_boxes=20000, log=print, init_anchors=None):
    import certificate_out as CO
    anchors = sorted(set(Q(a) for a in (init_anchors or [])))

    def worst_fn(A, starts=2, grid=12):
        ol, _ = goutleaf(inp, A)
        return float_worst_out(ol, starts=starts, grid=grid)[0]
    val = worst_fn(anchors, 3, 14)
    log(('gfloat', [str(a) for a in anchors], round(val, 6)))

    def greedy(anchors, val, cap, margin):
        while val >= margin and len(anchors) < cap:
            best = None
            for c in gmenu_for(inp, anchors):
                v = worst_fn(sorted(anchors+[c]))
                if best is None or v < best[0]:
                    best = (v, c)
            if best is None or best[0] >= val-1e-4:
                break
            anchors = sorted(anchors+[best[1]]); val = best[0]
            log(('ggreedy', [str(a) for a in anchors], round(val, 6)))
        return anchors, val
    anchors, val = greedy(anchors, val, max_anchors, float_margin)
    tries = 0
    while True:
        ol, plist = goutleaf(inp, anchors)
        try:
            tree, mx, nb = CO.build(ol, max_boxes=max_boxes)
            return dict(rows=[dict(kind='graded_out', parameters=p) for p in plist], tree=tree, maximum=mx,
                        boxes=nb, anchors=[str(a) for a in anchors])
        except CannotCertify as e:
            log(('cert-fail', [str(a) for a in anchors], e.args[0], e.value))
            tries += 1
            if tries > 2:
                raise
            anchors2, _ = greedy(anchors, 2.0, len(anchors)+1, 0.0)
            if anchors2 == anchors:
                raise
            anchors = anchors2


def verify_out(inp, record, model='outside'):
    import certificate_out as CO
    if 'rows' in record:
        sieve = []
        for rs in record['rows']:
            if model == 'outside':
                assert rs['kind'] in ('graded_out', 'graded_out_sec', 'graded_out_first')
                if rs['kind'] == 'graded_out_first':
                    s1 = safe_anchor(inp)
                    fm = 'outside_first' if Q(rs['parameters']['s']) == s1 else ('second' if inp.get('second') else False)
                else:
                    fm = 'second' if rs['kind'] == 'graded_out_sec' else False
                sieve.append(graded_row(inp, rs['parameters'], families=fm))
            else:
                assert rs['kind'] in ('graded_block', 'graded_block_fam', 'graded_block_famh')
                hid = rs['kind'] == 'graded_block_famh' and Q(rs['parameters']['s']) == safe_anchor(inp)
                sieve.append(graded_row(inp, rs['parameters'], families=(rs['kind'] != 'graded_block'), hidden=hid))
    else:
        assert model == 'outside'
        sieve = [sieve_rows(inp, sieve_test(p)) for p in record['sieve_parameters']]
    ol = CO.OutLeaf(inp, sieve, model=model)
    mx, nb = CO.verify_tree(ol, record['tree'])
    assert mx == record['maximum']
    return mx, nb


# ------------------------------------------------------------ fast staged driver for full covers
def staged_certify(inp, outside=False, log=print, margins=(0.97, 0.98, 0.99), max_rows=6, max_boxes=20000,
                   stages=None, mu_range=None, model='outside'):
    """Try small graded row sets first, then greedy additions; returns a record.

    Inside leaves always carry the family row (anchor s1).  Stage sets are
    reference anchors added to it; outside leaves use graded rows only."""
    s1 = safe_anchor(inp)
    if stages is None:
        stages = [[Q(19, 10)], [Q(19, 10), Q(23, 10)], [Q(3, 2), Q(19, 10), Q(23, 10)]]
    import os
    base = [] if (outside and model == 'outside' and not inp.get('second')
                  and os.environ.get('SIEVE_OUT_FIRST') != '1') else [s1]

    osec = outside and model == 'outside' and bool(inp.get('second'))
    ofirst = outside and model == 'outside' and os.environ.get('SIEVE_OUT_FIRST') == '1'

    def build(A):
        if outside and model == 'block':
            return gblockleaf(inp, A)
        if outside:
            fm = 'outside_first' if ofirst else ('second' if osec else False)
            return goutleaf(inp, A, model=model, families=fm)
        return gleafdata(inp, A, mu_range=mu_range)

    def worst(A, starts=2, grid=12):
        obj, _ = build(A)
        return (float_worst_out if outside else float_worst)(obj, starts=starts, grid=grid)[0]

    def certify_set(A):
        obj, plist = build(A)
        if outside:
            import certificate_out as CO
            tree, mx, nb = CO.build(obj, max_boxes=max_boxes)
            kind = ('graded_out_sec' if osec else 'graded_out') if model == 'outside' else 'graded_block_fam'
            if model == 'block' and any('vh' in sv for sv in obj.sieve):
                kind = 'graded_block_famh'
            if model == 'outside' and ofirst:
                kind = 'graded_out_first'
        else:
            tree, mx, nb = C2.build(obj, max_boxes=max_boxes)
            kind = 'graded'
        rec = dict(rows=[dict(kind=kind, parameters=p) for p in plist], tree=tree, maximum=mx, boxes=nb,
                   anchors=[str(a) for a in A])
        if mu_range is not None:
            rec['mu_range'] = [str(mu_range[0]), None if mu_range[1] is None else str(mu_range[1])]
        return rec
    tried = []
    A = None
    for k, st in enumerate(stages):
        A = sorted(set(base+[a for a in st if a > s1]))
        v = worst(A)
        log(('stage', [str(a) for a in A], round(v, 6)))
        if v < margins[min(k, len(margins)-1)]:
            try:
                return certify_set(A)
            except CannotCertify as e:
                log(('cert-fail', [str(a) for a in A], e.args[0], e.value))
                tried.append(A)
    # greedy additions from the last stage
    val = worst(A)
    if len(A) >= max_rows and val >= margins[-1]:
        raise CannotCertify('floating maximum above margin at the row limit', None, val)
    for _ in range(3):
        while len(A) < max_rows and (val >= margins[-1] or A in tried):
            best = None
            for c in gmenu_for(inp, A):
                if c <= s1:
                    continue
                vv = worst(sorted(A+[c]))
                if best is None or vv < best[0]:
                    best = (vv, c)
            if best is None:
                break
            A = sorted(A+[best[1]]); val = best[0]
            log(('ggreedy', [str(a) for a in A], round(val, 6)))
            if val < margins[-1] and A not in tried:
                break
        try:
            return certify_set(A)
        except CannotCertify as e:
            log(('cert-fail', [str(a) for a in A], e.args[0], e.value))
            tried.append(A)
            if len(A) >= max_rows:
                raise
    raise CannotCertify('staged driver exhausted')


RC_MU_SPLIT = (('0', '1'), ('1', None))


def rc_split_certify(inp, log=print, **kw):
    """rc inside leaves: certify each range of the first zero's normalized height separately."""
    parts = []
    for mr in RC_MU_SPLIT:
        log(('mu_range', mr))
        parts.append(staged_certify(inp, log=log, mu_range=mr, **kw))
    return dict(mu_split=parts, maximum=max(p['maximum'] for p in parts), boxes=sum(p['boxes'] for p in parts),
                anchors=[p['anchors'] for p in parts])


# ------------------------------------------------------------ case splits of hard leaves
def regen_split(inp, L, path):
    """Regenerate a sub-case of a captured leaf: the repository's split_specs applied along
    `path` = [(axis, mid, side), ...], then the same far/collective choices and the refined
    real/real third bound.  The children of a split exhaust the parent case."""
    from refinement_cover import split_specs
    sp = spec_of(inp)
    for axis, mid, side in path:
        kids = split_specs(sp, axis, mid)
        sp = kids[side]
    out = make_endgame(sp, L, parse_params(inp), inp['lambda_den'])
    if out is None:
        return None
    if 'far_parameters' in inp:
        out = replace_far(out, inp['far_parameters'])
    if 'collective_envelope' in inp:
        out = apply_collective(out, [r['parameters'] for r in inp['collective_envelope']['cohorts']])
    import third_refine
    return third_refine.refine_third(out)


def second_split_points(inp, k):
    """k-1 interior points splitting the reserved second-family interval into k equal parts."""
    lo, hi = Q(inp['ordinary_lower']), Q(inp['second']['hi'])
    return [lo+(hi-lo)*i/k for i in range(1, k)]


def split_certify(inp4, L, mids, axis='second', log=print, **kw):
    """Certify every sub-case of a split along `axis` at the given interior points."""
    children = []
    for i in range(len(mids)+1):
        path = []
        # child i: right of mids[i-1] (side 1) then left of mids[i] (side 0)
        if i > 0:
            path.append((axis, str(mids[i-1]), 1))
        if i < len(mids):
            path.append((axis, str(mids[i]), 0))
        inp = regen_split(inp4, L, path)
        if inp is None:
            children.append(dict(path=path, excluded_by_location=True)); continue
        log(('split-child', i, [str(m) for m in mids]))
        rec = rc_split_certify(inp, log=log, **kw) if inp['case']['kind'] == 'rc' else staged_certify(inp, log=log, **kw)
        rec['path'] = path
        children.append(rec)
    return dict(split=dict(axis=axis, mids=[str(m) for m in mids]), children=children,
                maximum=max(c.get('maximum', -1) for c in children), boxes=sum(c.get('boxes', 0) for c in children))


def verify_split(inp4, L, record):
    """Verify a split record against the captured parent leaf."""
    mids = [Q(m) for m in record['split']['mids']]
    axis = record['split']['axis']
    assert all(a < b for a, b in zip(mids, mids[1:]))
    assert len(record['children']) == len(mids)+1
    mx = -1; nb = 0
    for i, ch in enumerate(record['children']):
        path = []
        if i > 0:
            path.append((axis, str(mids[i-1]), 1))
        if i < len(mids):
            path.append((axis, str(mids[i]), 0))
        assert [tuple(p) for p in ch['path']] == path
        inp = regen_split(inp4, L, path)
        if ch.get('excluded_by_location'):
            assert inp is None
            continue
        m, n = verify(inp, ch)
        mx = max(mx, m); nb += n
    assert mx == record['maximum']
    return mx, nb


# ------------------------------------------------------------ outside-buffer splits
def regen_out_split(inp, L, path):
    """Outside-buffer sub-case: the repository's split_specs along `path`, then first_out_input."""
    nc = str(HERE.parent/'near'/'code')
    if nc not in sys.path:
        sys.path.insert(0, nc)
    import first_outside_blocks as fob
    from refine_probe import spec_from_input
    from refinement_cover import split_specs
    sp = spec_from_input(inp)
    for axis, mid, side in path:
        sp = split_specs(sp, axis, mid)[side]
    e = inp['extension']
    par = dict(method=e['variant'], gg=e['gG'], gz=e['gZ'], mix=e.get('mix', '0'), zeta=e.get('zeta', '3'))
    return fob.first_out_input(sp, L, 'outside_buffer', par, inp['lambda_den'])


def _split_paths(mids, axis):
    paths = []
    for i in range(len(mids)+1):
        path = []
        if i > 0:
            path.append((axis, str(mids[i-1]), 1))
        if i < len(mids):
            path.append((axis, str(mids[i]), 0))
        paths.append(path)
    return paths


def split_certify_out(inp4, L, mids, axis='second', log=print, **kw):
    children = []
    for i, path in enumerate(_split_paths(mids, axis)):
        inp = regen_out_split(inp4, L, path)
        log(('split-child', i, [str(m) for m in mids]))
        rec = staged_certify(inp, outside=True, log=log, **kw)
        rec['path'] = path
        children.append(rec)
    return dict(split=dict(axis=axis, mids=[str(m) for m in mids]), children=children,
                maximum=max(c['maximum'] for c in children), boxes=sum(c['boxes'] for c in children))


def verify_split_out(inp4, L, record):
    mids = [Q(m) for m in record['split']['mids']]
    axis = record['split']['axis']
    assert all(a < b for a, b in zip(mids, mids[1:]))
    paths = _split_paths(mids, axis)
    assert len(record['children']) == len(paths)
    mx = -1; nb = 0
    for path, ch in zip(paths, record['children']):
        assert [tuple(p) for p in ch['path']] == path
        m, n = verify_out(regen_out_split(inp4, L, path), ch)
        mx = max(mx, m); nb += n
    assert mx == record['maximum']
    return mx, nb
