"""Generate the self-contained Palomar Challenge from the library sources.

Challenge.lean consists of
* the definitions module `GradedNear/Defs.lean`, verbatim apart from its module header and title
  (it imports only Mathlib, and holds every definition the compared theorems use: a single module
  is elaborated identically in the Challenge, including the auxiliary proof constants that Lean
  abstracts from definitions and shares within a module);
* the statements of the compared theorems, extracted with their docstrings from their source
  files, with each proof replaced by `sorry`.

Each statement is placed in its source namespace, after the `open` and `variable` commands that
are in force before it in the source file (these are checked against the source). Generating the
file keeps the Challenge's definitions and statements textually identical to the library's.
`scripts/compare.lean` then checks the elaborated Challenge against the Solution.
"""
from pathlib import Path
import json, re

root = Path(__file__).resolve().parent.parent

DEFS = 'GradedNear/Defs.lean'
# (source file, theorem, namespace)
STATEMENTS = [
    ('GradedNear/Statement.lean', 'graded_near_lemma', 'GradedNear'),
    ('GradedNear/Response.lean', 'response_lemma', 'GradedNear'),
    ('GradedNear/ZeroForm.lean', 'graded_near_threshold', 'GradedNear'),
    ('GradedNear/Entry.lean', 'keptBound_single', 'GradedNear'),
    ('GradedNear/Entry.lean', 'keptBound_pair', 'GradedNear'),
    ('GradedNear/Entry.lean', 'single_zero_threshold', 'GradedNear'),
    ('GradedNear/Entry.lean', 'keptBound_double', 'GradedNear'),
    ('GradedNear/Entry.lean', 'keptBound_pair_neg', 'GradedNear'),
    ('GradedNear/Entry.lean', 'zeroTerm_conj', 'GradedNear'),
    ('GradedNear/Builder.lean', 'builder_threshold', 'GradedNear'),
    ('GradedNear/Builder.lean', 'pairExcess_eq_zero', 'GradedNear'),
    ('GradedNear/BurgessReduction.lean', 'burgessBound_of_primitive', 'GradedNear'),
    ('GradedNear/Conj.lean', 'zmult_conj', 'GradedNear'),
    ('GradedNear/Conj.lean', 'keptBound_pair_neg_real', 'GradedNear'),
    ('GradedNear/Cert/Bins.lean', 'near_row_of_bins', 'GradedNear.Cert'),
    ('GradedNear/Cert/Sound.lean', 'checkLeaf_sound', 'GradedNear.Cert'),
    ('GradedNear/Cert/Sound.lean', 'checkLeaf_lt', 'GradedNear.Cert'),
    ('GradedNear/Cert/Sound.lean', 'certified', 'GradedNear.Cert'),
]
# the file-level `open`s of the Challenge (those of Defs.lean); every statement's source file may
# only use a subset of them before its namespace
GLOBAL_OPENS = {'open Complex MeasureTheory',
                'open scoped ArithmeticFunction.vonMangoldt ArithmeticFunction.Moebius'}
GLOBAL_OPEN_NAMES = {'Complex', 'MeasureTheory', 'scoped', 'ArithmeticFunction.vonMangoldt',
                     'ArithmeticFunction.Moebius'}

# Palomar requires every Lean file to use the module system (PalomarPolicy CONTRIBUTING.md,
# "Lean source requirements"): the Challenge is a module importing only Mathlib, and its
# declarations are public with exposed definition bodies, as in `GradedNear/Defs.lean`.
MODULE_HEADER = 'module\n\npublic import Mathlib\n'
PUBLIC = '@[expose] public section\n'

HEADER = MODULE_HEADER + '''

/-!
# The graded near lemma and the leaf-certificate checker (Palomar Challenge)

This file is generated by `scripts/make_challenge.py` from the definitions module
`GradedNear/Defs.lean` and from the statements of the compared theorems. It contains two parts.

**The graded near lemma** (Theorem 8.4 of the paper `paper/linnik399.pdf`
in this repository), conditional on four printed results stated as hypotheses (`XylourisLemma31`,
`XylourisLemma32`, `BurgessPrimitive`, `GrahamEstimate`):
* `graded_near_lemma`: the quadratic-form inequality for prime-sum responses;
* `response_lemma`: a response is bounded below by the zeros it keeps;
* `graded_near_threshold`: the zero form, the threshold form (T) of a row with each entry's
  feature computed from its kept zeros;
* `keptBound_single`, `keptBound_pair`, `keptBound_double`, `keptBound_pair_neg`,
  `zeroTerm_conj`, `single_zero_threshold`: the entry bounds of the rows (paper §9.4), `F(hi - s_j)`
  for a kept zero at the entry's height, plus the terms of the other kept zeros;
* `builder_threshold`: (T) in the normalization the leaf builders use;
* `pairExcess_eq_zero`: same-character pairs at separated heights carry no pair excess;
* `burgessBound_of_primitive`: Burgess's bound for all non-principal characters (`BurgessBound`,
  used internally) follows from Heath-Brown's printed statement for primitive characters;
* `zmult_conj`, `keptBound_pair_neg_real`: for a real character, conjugate zeros have equal
  multiplicity, and the shifted `rc` entry bound holds without a multiplicity hypothesis.

**The leaf LP certificates** (paper §10):
* `Cert.near_row_of_bins`: binning the entries of a row conservatively into the columns of a leaf
  turns (T) into that near row of the leaf LP (`Cert.Feasible`), at column values shared by all
  rows;
* `Cert.checkLeaf_sound`, `Cert.checkLeaf_lt`, `Cert.certified`: if the exact checker
  `Cert.checkLeaf` accepts a certificate with value `v`, then every feasible point of the leaf
  LP has objective at most `v < S`.
-/
'''


def scope_before(text, pos, ns):
    """`open`/`variable` commands in force at `pos` inside `namespace ns`, and the file-level ones."""
    head = text[:text.index(f'\nnamespace {ns}\n')]
    file_opens = [l for l in head.split('\n') if l.startswith('open ')]
    inner = text[text.index(f'\nnamespace {ns}\n'):pos].split('\n')
    cmds, depth = [], 0
    for l in inner[2:]:
        if l.startswith('namespace ') or l.startswith('section'):
            depth += 1
        elif l.startswith('end '):
            depth -= 1
        elif depth == 0 and (l.startswith('open ') or l.startswith('variable ')) and not l.endswith(' in'):
            cmds.append(l)
    return file_opens, cmds


def statement(path, name, ns):
    text = (root / path).read_text()
    m = re.search(rf'\n(theorem|lemma) {re.escape(name)}\b', text)
    assert m, (path, name)
    start = m.start() + 1
    # the docstring immediately before
    before = text[:start].rstrip()
    assert before.endswith('-/'), f'{name}: no docstring'
    doc_start = before.rindex('/--')
    stmt_end = text.index(':=', start)
    stmt = text[start:stmt_end].rstrip()
    assert ':=' not in stmt
    file_opens, cmds = scope_before(text, doc_start, ns)
    # file-level `open`s beyond the Challenge's own are repeated inside the statement's block
    extra = [o for o in file_opens if not set(o.split()[1:]) <= GLOBAL_OPEN_NAMES]
    return extra + cmds, text[doc_start:start] + stmt + ' := by\n  sorry\n'


def main():
    defs = (root / DEFS).read_text()
    assert defs.startswith(MODULE_HEADER), 'Defs.lean must be a module importing only Mathlib'
    assert [l for l in defs.split('\n') if re.match(r'(public |meta )*import ', l)] == \
        ['public import Mathlib'], 'Defs.lean must import only Mathlib'
    for opens in GLOBAL_OPENS:
        assert opens in defs
    rest = defs[len(MODULE_HEADER):].lstrip('\n')
    assert rest.startswith('/-!\n'), 'Defs.lean: module documentation after the header'
    doc_end = rest.index('-/\n') + len('-/\n')
    doc, after = rest[:doc_end], rest[doc_end:].lstrip('\n')
    assert after.startswith(PUBLIC), 'Defs.lean: `@[expose] public section` after the documentation'
    title = doc.split('\n')[1]
    assert title.startswith('# '), title
    doc = doc.replace(title, '#' + title, 1)
    body = after[len(PUBLIC):].lstrip('\n')
    parts = [HEADER, PUBLIC, doc, body, '/-! ## The compared theorems -/\n']
    for p, name, ns in STATEMENTS:
        cmds, st = statement(p, name, ns)
        block = f'namespace {ns}\n\n' + ''.join(c + '\n\n' for c in cmds) + st + f'\nend {ns}\n'
        parts.append(f'-- from `{p}`\n' + block)
    challenge = '\n'.join(parts)
    out = root / 'Challenge.lean'
    out.write_text(challenge)
    n = challenge.count('\n')
    print(f'wrote {out} ({n} lines, {len(challenge.encode())} bytes)')
    assert n <= 1000 and len(challenge.encode()) <= 100 * 1024, 'Palomar Challenge limits exceeded'
    cfg = json.loads((root / 'comparator.json').read_text())
    names = [f'{ns}.{name}' for _, name, ns in STATEMENTS]
    assert cfg['theorem_names'] == names, 'comparator.json theorem_names out of date'

if __name__ == '__main__':
    main()
